version: 0.0
os: linux
files:
  - source: /
    destination: /paperhubapi
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
    - location: scripts/run_migrations.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root